# Generated by Django 6.0 on 2026-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tempo_preparo', models.IntegerField()),
                ('descricao_curta', models.CharField(max_length=150)),
                ('historia', models.TextField()),
                ('imagem', models.ImageField(upload_to='receitas/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
