# Generated by Django 6.0 on 2026-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
