# Generated by Django 6.0 on 2026-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_receita_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('tradicao-baiana', 'Tradição Baiana'), ('terreiro', 'Receita de Terreiro'), ('ancestral', 'Receita Ancestral')], default='tradicao-baiana', max_length=50),
        ),
    ]
