# Generated by Django 6.0 on 2026-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_receita_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['-criada_em'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(blank=True, verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True, verbose_name='Modo de preparo'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('tradicao-baiana', 'Tradição Baiana'), ('terreiro', 'Receita de Terreiro'), ('ancestral', 'Receita Ancestral')], default='tradicao-baiana', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao_curta',
            field=models.CharField(max_length=150, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Receita em destaque'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='historia',
            field=models.TextField(blank=True, verbose_name='História / Contexto cultural'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(upload_to='receitas/', verbose_name='Imagem da receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.PositiveIntegerField(verbose_name='Tempo de preparo (minutos)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
