# Generated by Django 6.0 on 2026-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_receita_options_receita_ingredientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Página Institucional',
                'verbose_name_plural': 'Páginas Institucionais',
            },
        ),
    ]
