# Generated by Django 6.0 on 2026-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_paginainstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da história')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('protagonista', models.CharField(max_length=150, verbose_name='Nome da protagonista')),
                ('local', models.CharField(blank=True, max_length=150, verbose_name='Local / Território')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='historias/', verbose_name='Imagem da protagonista')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo (para listagem)')),
                ('texto', models.TextField(verbose_name='Texto da história')),
                ('publicada_em', models.DateTimeField(auto_now_add=True, verbose_name='Publicada em')),
            ],
            options={
                'verbose_name': 'História',
                'verbose_name_plural': 'Histórias',
                'ordering': ['-publicada_em'],
            },
        ),
    ]
