# Generated by Django 6.0 on 2026-01-16 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_historia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-publicada_em', '-criada_em'], 'verbose_name': 'História', 'verbose_name_plural': 'Histórias'},
        ),
        migrations.AddField(
            model_name='historia',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criada em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia',
            name='publicada',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='publicada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='texto',
            field=models.TextField(verbose_name='Texto completo da história'),
        ),
    ]
