# Generated by Django 6.0 on 2026-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_historia_options_historia_criada_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='publicada',
            field=models.BooleanField(default=True, verbose_name='Publicada'),
        ),
    ]
